theme: jekyll-theme-cayman
title: Yongsen Ma
description: Yongsen Ma | Computer Science | William & Mary
institution: Computer Science Department, College of William and Mary
address: Williamsburg, Virginia, USA